language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-healpy
# command to install dependencies
install:
 - python setup.py install --no-downloads
script: true
notifications:
  email:
    recipients:
      - jo.bovy@gmail.com
    on_success: change
    on_failure: change
